/*
 * vehicleTrackingSystem.h
 *
 *  Created on: Aug 28, 2023
 *      Author: muham
 */

#ifndef DRIVER_VTS_VEHICLETRACKINGSYSTEM_H_
#define DRIVER_VTS_VEHICLETRACKINGSYSTEM_H_

#include <stdint.h>

typedef enum {
	REQUEST_TYPE_IDLE,
	REQUEST_TYPE_IN_PROGRESS,
	REQUEST_TYPE_WAIT_PROCESS,
	REQUEST_TYPE_TIMEOUT_PROCESS,
	REQUEST_TYPE_LOOP_PROCESS,
	REQUEST_TYPE_BLOCKING_PROCESS,
	REQUEST_TYPE_WAIT_CALLBACK_PROCESS,
	REQUEST_TYPE_WAIT_INTERRUPT_PROCESS,
	REQUEST_TYPE_WAIT_RECV_COMPLETED_PROCESS,
	REQUEST_TYPE_WAIT_TRANS_COMPLETED_PROCESS,
	REQUEST_TYPE_WAIT_CALCULATE_PROCESS,
	REQUEST_TYPE_WAIT_PREPARE_PROCESS,
	REQUEST_TYPE_WAIT_SEARCH_PROCESS,
	REQUEST_TYPE_WAIT_CONNECTING_PROCESS,
	REQUEST_TYPE_WAIT_GSM_PROCESS,
	REQUEST_TYPE_WAIT_MQTT_PROCESS,
	REQUEST_TYPE_WAIT_OBD2_PROCESS,
	REQUEST_TYPE_WAIT_BLE_PROCESS,
	REQUEST_TYPE_WAIT_MEMS_PROCESS,
	REQUEST_TYPE_WAIT_DEBUG_PROCESS,
	REQUEST_TYPE_WAIT_RTC_PROCESS,
	REQUEST_TYPE_WAIT_MQTT_PUBLISH_PROCESS,
	REQUEST_TYPE_WAIT_FTP_PROCESS,
	REQUEST_TYPE_WAIT_TFTP_PROCESS,
	REQUEST_TYPE_WAIT_GPS_COLD_START_PROCESS,
	REQUEST_TYPE_WAIT_GPS_WARM_START_PROCESS,
	REQUEST_TYPE_WAIT_GPS_DEADLOCK_PROCESS,
	REQUEST_TYPE_WAIT_GPS_2D_3D_FIX_PROCESS,
} iwdgRefreshRequestType_e;


extern void VTSInit(void);
extern void VTSControl(void);

extern void virtualIwdgRefresh(iwdgRefreshRequestType_e requestType);

extern void VTS_Virtual_SysTick_Handler(void);
extern void VTS_Virtual_UART_RxCpltCallback(void *huart);
extern void VTS_Virtual_TIM_PeriodElapsedCallback(void *htim);
extern void VTS_Virtual_GPIO_EXTI_Callback(uint16_t pin);

#endif /* DRIVER_VTS_VEHICLETRACKINGSYSTEM_H_ */
